package api

const (
	LUAVALUE_NONE LuaValueType = iota - 1 // -1
	LUAVALUE_NIL
	LUAVALUE_BOOLEAN
	LUAVALUE_LIGHTUSERDATA
	LUAVALUE_NUMBER
	LUAVALUE_STRING
	LUAVALUE_TABLE
	LUAVALUE_FUNCTION
	LUAVALUE_USERDATA
	LUAVALUE_THREAD
)
